### ISSUE TITLE
Provide support for windows OS

### ISSUE THREAD

**Issue by SarthakMakhija** [SarthakMakhija/goselect#7]
goselect should run on Windows OS. At this point, goselect runs on MacOS and linux with ARM64, AMD64 and i386 processor.

One of the main challenges in ensuring that it runs on windows is the way golang exposes 
- CreatedTime, ModifiedTime, AccessTime from file API
- The way `user and group` information needs to be found in windows
- The way `block` information needs to be found in windows
- The way hidden file are found in windows (`hidden_windows.go already exists`)

In order to provide support for windows we must make the following changes:

**Changes**

1. Provides CreatedTime, ModifiedTime, AccessTime for windows by providing a go file built for windows
2. Provide user and group information for windows
3. Provide blocks information for windows
5. Ensure all the existing tests run
6. Create a build pipeline for windows and all the tests should run

**Reference**

1. Look at the platform package inside context

**Comment by bryonye** [comment]
Hey, is this still available? I’m happy to have a go.

**Comment by SarthakMakhija** [comment]
Sure, the change is tricky though :)

Please do let me know if you would like to pair or collaborate somehow ..

**Comment by SarthakMakhija** [comment]
@bryonye Hey .. I would like to close this issue .. We have added support for Windows OS (AMD64) as a part of 0.0.7 release

**Comment by SarthakMakhija** [comment]
Closing the issue .. Windows support is available now
